# Generated by Django 5.2.13 on 2026-05-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlterationsApp', '0002_remove_order_email_remove_order_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
