# Generated by Django 5.2.14 on 2026-05-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlterationsApp', '0003_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='alteration_type',
            field=models.CharField(choices=[('hem', 'Hem'), ('resize', 'Resize'), ('repair', 'Repair'), ('shorten', 'Shorten Sleeves'), ('take_in', 'Take In')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='chest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='hips',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='inseam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(choices=[('dress', 'Dress'), ('pants', 'Pants'), ('shirt', 'Shirt'), ('skirt', 'Skirt'), ('suit', 'Suit')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='material',
            field=models.CharField(choices=[('cotton', 'Cotton'), ('silk', 'Silk'), ('denim', 'Denim'), ('polyester', 'Polyester'), ('wool', 'Wool')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='waist',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
