# Generated by Django 5.2.13 on 2026-05-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlterationsApp', '0004_alter_order_alteration_type_alter_order_chest_and_more'),
        ('AlterationsApp', '0004_order_assigned_staff_alter_order_customer_name'),
    ]

    operations = [
    ]
