# Generated by Django 5.2.14 on 2026-05-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlterationsApp', '0005_merge_20260507_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shoulders',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sleeve_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='alteration_type',
            field=models.CharField(choices=[('hem', 'Hem'), ('resize', 'Resize'), ('repair', 'Repair'), ('shorten', 'Shorten Sleeves'), ('take_in', 'Take In'), ('bust', 'Bust adjustment'), ('waist', 'Waist Adjustment'), ('hips', 'Hip Adjustment'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(choices=[('dress', 'Dress'), ('pants', 'Pants'), ('shirt', 'Shirt'), ('skirt', 'Skirt'), ('suit', 'Suit'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='material',
            field=models.CharField(choices=[('cotton', 'Cotton'), ('silk', 'Silk'), ('denim', 'Denim'), ('polyester', 'Polyester'), ('wool', 'Wool'), ('other', 'Other')], max_length=100),
        ),
    ]
