# Generated by Django 5.2.14 on 2026-05-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlterationsApp', '0006_order_shoulders_order_sleeve_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bust',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
