# Generated by Django 5.2.13 on 2026-05-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlterationsApp', '0006_alter_order_alteration_type_alter_order_description_and_more'),
        ('AlterationsApp', '0007_order_bust'),
    ]

    operations = [
    ]
